#!/bin/sh
### BEGIN INIT INFO
# Provides: start-zookeeper stop-zookeeper
# Required-Start: 
# Required-Stop: 
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: Zookeeper
### END INIT INFO

case "$1" in
"start")
  $KAFKA_HOME/bin/zookeeper-server-start.sh -daemon /etc/opt/kafka/zookeeper.properties
  ;;
"stop")
  $KAFKA_HOME/bin/zookeeper-server-stop.sh
  ;;
"restart")
  $KAFKA_HOME/bin/zookeeper-server-stop.sh
  $KAFKA_HOME/bin/zookeeper-server-start.sh -daemon /etc/opt/kafka/zookeeper.properties
  ;;
*)
  echo "Usage: $0 { start | stop | restart }"
  ;;
esac
exit 0
